### PR TITLE
Add more SKY130 cell libraries.

### PR DESCRIPTION
**Pull request by mithro**
Also increase the documentation about skywater process.

### CODE REVIEW

**Comment by antonblanchard** [comment]
Hi @mithro the CI picked up a couple of linting warnings:

```
./vlsiffra/tech/sky130.py:130:66: W291 trailing whitespace
./vlsiffra/tech/sky130.py:144:68: W291 trailing whitespace
./vlsiffra/tech/sky130.py:155:68: W291 trailing whitespace
./vlsiffra/tech/sky130.py:170:1: W391 blank line at end of file
./vlsiffra/tech/sky130hd.py:2:1: F401 '.sky130.SKY130HDProcess' imported but unused
```

**Comment by mithro** [comment]
This change needs #31 and #29 to be merged first.

**Comment by mithro** [comment]
> Hi @mithro the CI picked up a couple of linting warnings:
> 
> ```
> ./vlsiffra/tech/sky130.py:130:66: W291 trailing whitespace
> ./vlsiffra/tech/sky130.py:144:68: W291 trailing whitespace
> ./vlsiffra/tech/sky130.py:155:68: W291 trailing whitespace
> ./vlsiffra/tech/sky130.py:170:1: W391 blank line at end of file
> ./vlsiffra/tech/sky130hd.py:2:1: F401 '.sky130.SKY130HDProcess' imported but unused
> ```

These should be fixed now.

**Comment by antonblanchard** [comment]
Looks good!

**Pull request merged**
